apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: city-foundation-next
    source: nadaciamesta.bratislava.sk
  name: city-foundation-next-mailgun-secret
  namespace: standalone
spec:
  encryptedData:
    MAILGUN_API_KEY: AgCxeIRhJBMCOVxBOAg1xha8JVkix9MP7EqCXY/sMGVhSBj+BP1zCYj6iiyW9tbm3Z/9OPcC2WqcI0AKDvDOtCXynVhD+hRKzNF2XxKb+9lLZr6OsVGJC+5bN1bpHppQZOagenXkOzk8kfHrl0W+7BoX3vhaRlu24TXpZ4UuIf0gTqeRfmJcsOrWcAD/krlaIqI5T2aT0ddA22vg0h+/tI6SkZS+Vou6+pKU1OOXxY3t46llzatjc2tgH8367xXYtwUELpl6aRpnKzAK8tjf3dSvoGOj3lbSkYbB2ktGVfaoncdT7ayMXk3VJtZZyRbA1CWNWAX2LlfOiLlN9+/zgL+ucrFMK4UymO7nll7FKzncJQFRl5mzJn6dnf8C/yLgspkFrzEE7gBhcQInWYRxb3IkA/+o5aJdgCmhGQixvGYI3ajLmJNRh09HGGw1MNcGfjBW53tW/A6r3Ktwh7D+flCTJd4Qhom3KODDCCxVrIf7JL37oRi/A9g5Xk16vzgvdCm+BybL3mwDfQuAPZEWglUNEiiqunSXqorSvtILbXeniCjF6RUbE7mB65St9HQkglh9RrJ7zA6nIrDovcmZpD/+1QTydj+6f29eDgkySTYM/JWl8AEoq2hd6qQTWddsK8CfQZFCUY/iYAZDlkSHtYg1pa4T98dDpCQznU/aTOycYJBsvJwugKvsU5dWb4k8vlxJtMSdHwbPLymUHVNkRAEuaKWQFp98ELA8CbJF0/h+ImGrXND6T5+ASS7YvRRIZWmq7Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: city-foundation-next
        source: nadaciamesta.bratislava.sk
      name: city-foundation-next-mailgun-secret
      namespace: standalone
