apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: city-foundation-next
    source: nadaciamesta.bratislava.sk
  name: city-foundation-next-mailgun-secret
  namespace: standalone
spec:
  encryptedData:
    MAILGUN_API_KEY: AgBg8KUiEUXB/mfycqJLFkbK75y+8k0sdNgchDGRgUIjuLdpXs57CCxmHXArkgE3RS+WQwh6mgrnC0YbnusWNx66+FfmEGK83eTFVp1pPvNvU4h2vo3aiI2lfUxKx42y7uy1sCpWVSfQ2pJLsJzTkVobsb+liwGjFOYyl8s8vKMMpPACuGdnJSCAq5PrH8PS6HxXT5q5kMsL0NjSIGOAPzDL2j7g/TSsvhyyykEDfE+XwIHF/h43Uz305H6X+bc8AZyxQOs99igmz3Wuz+m//T3i4zg5z0C/fGov1MY6m0cvLRHJEFNzh7IRN0cGB6v26Wj4kmnQ5iCtHJWgiWM8KhvD8gTrGbGaZoGxSSUeHawC83mJqwh1ZXXhyCqIc/sIaIG99tzuGuR/3LxBQ79AlLMCk8kxVgPl9ltYZAdKjm65UxwN6pXsYLm0jB3Cf4XUhGWBKOnob5Uf+XAteIy1eTvuFipsz+qrcP94AVGE2F76AaSMZ1N7T1ayGZVA27D69CmKkBURbEUysABKMv5AN8Bd7/okwvLXNapqLA8Payc0x+Sm8a35KPUdE8xfeqB0PO8bqGgOJGfP2qw1U0oKG4PQAZ3wI6xJxp5EhqvoI9yevFjBmdDe1qTzwhMjuci7XtW5JJ1pFggt+SHof/3QRgtRfM1oiUpzeFF0gbm7ErwxiHxx1AyLE4+mUsgppl7c8PhkfrjxIH1JPh5021NjEHpdPlKmyFy/nmWFbRkEJOkRqfyuul0W1/o6RstObZm4j9iPZg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: city-foundation-next
        source: nadaciamesta.bratislava.sk
      name: city-foundation-next-mailgun-secret
      namespace: standalone
