apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: city-foundation-next-mailgun-secret
  namespace: standalone
spec:
  encryptedData:
    MAILGUN_API_KEY: AgCSSS+oZ5srTXcHket3Vm2+Te6CVNuhBrnnkU3B70Nazy9/Wi/oj8Iu6q1rnxHmhRPLLAdFKrMztjAydOvahzRlP8ubt7m9fss+NkJug2U4nm0J8kSniYkSp8c/DyYs46o5cWeWzfjlEttJJP5AXt+6B7eKPC8fQaTRy45S4jAAmARstfKYYkWiFNrpsGQHeA2HKDJP9WYwL6zT5KvXgIiI4PBJY158q6Ta6XxQVYNk2pUcEcuihpS+NqcQe4xrtXqXYp5hPooO2Dofj2gto2acnIZ4rapeAq2L5iC4wDqr1zz2WJBkoFB7jMEXGyHYRflkr0X4jeG60LiYQ2mS66MCYN5uM9n42mblon+r7LkPiK3vX0nzihN/iZPoAbClkxUrDDnW8KceU2+f0QpiiFrEvkVdR+KBGTvS+/JYruZDW1/Fs5mtswWmFkxBC49FbWaM47Eey96s8+gtwCMWlRATKs87hQI4kDlMlwxaHDZPhW7jTiow6w/HTDBhajAxgqcMIm4966MR2Pv8nVgQCiNLJQ0oYFU8435RrmZCqWZBASgXYCOrw1jFgb/ldAauVsS4gluBufUJP5BkiLj8B+qXZdgTAUS90r8Eoj7k8imt5ODkCMpIaCoQ+ks/O7bzjTvjr24n14OlJtd6gLbq4PjitOwlbfdT2oBe/h0ZSA65jLgjIRIcqRf1dcBo2qBu5SVX0sDWebHvVfoFInxeHzhhJ8mHplK1eFI1bG8KKVx85FNP9Z3c0WiDagUZvH119LP0sw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      labels:
        app: city-foundation-next
        source: nadaciamesta.bratislava.sk
      name: city-foundation-next-mailgun-secret
      namespace: standalone
