apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: city-foundation-next
    source: nadaciamesta.bratislava.sk
  name: city-foundation-next-mailgun-secret
  namespace: standalone
spec:
  encryptedData:
    MAILGUN_API_KEY: AgDSH7N/2+3vywVW9NmqAs6NkHFsevOoBAFjNIl4n8gyB8w2HRbqbLrZWzpEZl4TDZCBSUGgOqKGuiM4MeWLitXCUZOP0OvzpJVt3FmYfR5DFHcfTgrV42fPvKtFW+NPMNeSFzBQGZISmg+1Vooh9SpH/zFanb6FqkDrGnnf5V5PrpZaIIRUGCXcFBmBkssidTu3cAWsrSLYpsmTVa1MOUlvjzmKtP+GHY2FRbdjQUPxpeENL/1m7lIaiczA55c4rv3ef8Yc299AdcdLD0NKeK1R65aKWGHjXWZpdtpO4jAPLsK8Mdh1eKKeMBrThGmhOGETFB5sGqZFbwlvTvflctAz5yrupYVagXwtjQ/KeNS/yM2byCLN/BDshdE9l/neDFICXxLyuQxcdZ5zUt6y3GYqwk2PFJOfZfFpwf4vj2dDf6NXyY81D09nTLIJI48uDUTsrzSsygoel8dFrChX9b9MOd30MhrUCDVaJpwllxYo32iwxdsgns38zIpZN8Knyan8DRwrf30ZM22R0XpUCTR54n7CtA9sPvJK6VNa69QEClMAnldW7oIWXe8XLYKp96Z+2B2xBFCtYkEt801JQ7pYVsISEyfGUs4phV2TEEHQaCJJPRhRSYeexn1yew3vr5EsXqC0jV8hEbE8x1f/wNoC98oC+kjlXsg/m2W8vI9ORrwDc3tYGh9Ov7125u7E9N1TQwcQeRSDnHc9G8svvPi0sCeockZ1r4N457wD6Qx1nvXLVQlI9ojxVRJ3Qopc4fxrXQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: city-foundation-next
        source: nadaciamesta.bratislava.sk
      name: city-foundation-next-mailgun-secret
      namespace: standalone
