apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-foundation-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgApM92Z7eMAaKl3HhiYsiaayrUIlRy5aATBYn2sMn62FnVEoqO7eA7F0CM1hRtXqx7jBXPDJeuWQJaE5yB4kZMVOoR4TIJRnLU6DD5zPvzUn64HETvWI0G5Cn/fqwinXMKR/qL3avfUo4zkBRPTEFCXIdRwwPKG/U1Abt2c1UY56BMQwqqhIW9DQ6mpE5fY8x6Ja4qiB8sVL1wAwDbt2+QEcbqv9NL8QDUPdNr5SgQxECzVLqfhO/jdGhEl4TJUVsYhz/CvUkdxlgAJAmVkxTcuS2rnM8S0Y+bxGFk5z6qc4SWZVd1MZiWAzzFwJwMRMo6PZe1CNWIIOygTFYBlN/uuuQixA83ufTaZggCfsEV7mtCVtCIeByOwaOPyEU9HlJyEgoxM/AjYzeoSBHmgD7HwAiV1eX/p+y/qnIHQBO0cVqU2yuovsjoR9icYjWthOZG23d+WspGeA17HQ0vRtedvVAjzEHDa1SdfHhuoZ0YJEuaxu1SIB42a4vWQJEz5jW99D5R5QJxwnKk5rf1JCNV1NnNQH2HZtPqrcl3MYowT/RNnrxcU/U/QPfVxZgK99+YjbyVuzNL1Kr7KN6tpQtkSgXO6u7FgX+RCBpsMNA6JntOfa9ypy5ovji00lgQtu7aHqNGSkxg3q+0CAta7GrzhLAniuhw3gO1x3tv6oFfcD2zla2cnDaRLuGFJ1Va2RPsHjM6F8ni5g7U4AXpo9XLXN5lkzcwXDb1/lbk=
    POSTGRES_PASSWORD: AgB17K8J3LgL2pFmecMKDY0R9/vef54C0mi/284uY/K30bSp3pUnxO2LXpMjhTcvEGuodALxkbhERBU6QRIoczG4qxu1hZkXqR3dm7T/imhdJFCS+mSWQS+EEXLKIBIkqUmj0nqdYpF6dv+igRaqQjQzY75k2xUMpl66TDhH/nXt40uf1maZCoA5UyS98dC6WK+x3hFFu2EIbElRYc4HC+rnhqW1avPtpJnOy9gAbQZ2r7cQYFlgySTNv8H/aeFZiIvQhKvbcK5MhaoqDzEOdurk+Y72Yc06/iUJlt79A1SYkYZ8hHt1X/qwgT5gdfuxWarC9jvRfvyjxdRdz3ZJ9EMxpUPERtJyeIzi7wNvVlg8ULNjWoyPamr1CI+betMtRRPlyU19HIhv03Rrn4vXSYPPULspSLj8V8ZJCPviQBVhX9t0ErvHnl3if7Nr+AZRgS+yGr9KORm91yF2Ack0w6xQBfGWNW+DBt+yIT6GS3v5kYWguUPzn7fTTrTyh2Qaf4IDgHZL2kn2ocbQ3nDa2ZoJChQgimhbCKSJR4zcarm12a+FHpm4HiS1ATjyLkB07U9I+42O5na2Q9t70gjhxSfWIUBeYJ9+BJ2Z2abV2KtyjOfR3bJb+0hwqJleQuTbX6LI98KTpSJvIebxAIoA5m5bgMJ1IyPdyZdxQUFzSzlYSvESrsProHTpi/ANKhjkn/xPVqKq/Itguo+1sfoAVZ7LwM/xRZEMUQd2ilU=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-foundation-strapi-database-secret
      namespace: standalone

