apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-foundation-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgAo4MctZdKcI0r7lemTf3yjV3k617irtZhzpqCiyWeH8et40vB8mqCuLrJwRzTrG8qAqFsEULwRjHQnmjlHSYr2A8+o91UMtRs8cYFV3ZTnG6xrKc4QpP+3QRPtWS82LBw2O4Pwo8qPdT3XSqM8v+XQvtGqSNSjOLEs7rjPdnYcwQJ/Rk8LQCLi8odoePAc/Q0C4+DrTzjKqN2gKV1oOS7iGYK4wn6i7SinmmEGQ9nZhXxbhj8aZMCe/CYerz7A9WI70+RVQ9rncYTWwkTr3gtNWVmxbVkM5JIyordKhxg5/6sydf+KqhfyvUBrLRZFrGXXDNjx/TvNPNR6B7YBrHdQ49D+qmDUlKJixRjQcvXqdA2BrqBxcvVvz0/UcOdHgXYT4Kp4sYgLPsSeFqTK6xbsuDo3cIifbXLbNezpgANPHbh7sU6vMTc73hgMhuoiJR218pdt9l/Ko5sJgMsiDA6WY75Ib2jcGGuHvRCcO74kz9ON7PtlN5qebpX0W50HKnnkAKB5W6FiPy+VYWUqdRS5oOYIP34tYaoV4QPI1MOJKLarTVHKWMRzkavExwwO/ujvsz54uOEtlNIL3Soh3VxTrznpgxPSX4S6Y0rQ6w6rEniHEEkofMVKz+/at8hQ5cg+IPoPPuLAQTepLo5bAjlJvL0Or4VewlmrBeDXpALjLuZXxeC63kOhgAz+eJH+Ib1B2gtq0A+IMv+vCTqFRiLQUpKumLG6lV9uOYAzEg==
    POSTGRES_PASSWORD: AgCxNeBppsXO5C5ZEcpPKGqb3N+lxiulpAppUU8WOUgEu9b36QeUJ6ht7yf0exc5Cs4Z3mywGt/7kOvOpgtClPoF15YuPlE3ZXaerG1WzMztS0RnFP0J32YUb9d1rM2ghUfuHxT05nuPLMqFjiQ1ah8beWF54RLjM925P9v7CIWMAP2qdqH00vLpDOFwcGHtqkL6bETyNBdirJMEIVTLqtPMB6NIiPJZEyM703JWeGsr5xpkQAkvaVDXHXw/UZsKjZaGFAfKn6T9jd1j3ZYIWWuOf34lU4MyYmbK50U4Q/E0i4fKGGMgNjGFGIXKkVVOkzdhhTIvmYjZKMBA3ytQDMRGcpcgQKRYyNwK76KGCKppZx7IJ4BkUt734KGk5099rPCoymrEbysgfkuRY3Xc0LBXGoqJB0fvvsUmsFc7jyLi57X7Z3LxN/4mg+/XluGahbEGVBoP5Pmaz38HiRkYICZnMqxtFp1AliNx30jLNdxlWSmjUPBrJo8/pH0JZKQD+7Y1nYE5NAlaWA+mW/sayXN2aAmaIrlrtB9KFBAZGOixtLc/PIPOpsHNHNS6BSlYoZrJX0fGAChMkjR5oasbLjT9AACSyedv6Oh/DpOXVsZ8dklpK5mGs5jJ1Ygm3St6SxS6NMjbFvIh3tp9Etqmrf1v9clYDSC0hMQ6edV+JQy5/ZW44/iiWySv9pFq93QZsngUzaEJmyCjF3Ujab0w4pmZimTU6RMNHSpdBWw2Lg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-foundation-strapi-database-secret
      namespace: standalone

