apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-foundation-strapi-database-secret
  namespace: standalone
spec:
  encryptedData:
    DATABASE_PASSWORD: AgAPpyYQOsLkprF+hXA+Jsrmf/vS0c6J3SnQSi9bhLycocW2y8nnoGPK2vUlII0POwUopwxoqcoYDQCqfIR5iihMAJUaHhXGnV06a1E7DzH3LZMTzkSgtev2BtxlPRQhZnlDm4CIYekA3OSdpJAuWoDxclfR1yqMAAqDPMHwO7211RlTe+FBjvgz2JarmnaT5rEIMUyCPT5kWeNTtAd+ZNRjnKHktLWiANHyRCFleyo0UGpXRmA+WtbWP61VVNB6zaUgdSvvSWGFsTGN/2cc6NPDGGUL4zv+7XcLrTzJYv8W7MEPuHyTGBotPLfPruripjIp9kKn6ZaRRGvHjWjoMnaTfNwSamcaZa8M9HhU3hoaTNqYEeS9BmMiZwgeDMw/SXejGS3aMsCpvjYaBlBhnm+EigZYCOaC4YajoQ03Sjq+F6+jQX8juJUEpXw9F0cZOmQvNZqHuBqrJVW+n13SHbvGfXWsjksQyhoPcsjrcAfrAPWN4iVRUdrT/6PqCTd3iNq7fIOwxqMAvpsUBKcxhVkworxzAlNh7Y0Fr6JEibSZoJS9aF3PQZlVqUH3ilS0cSJfzv61W1pCsgOxuAhG/xtl1fy5WGuhM78VwTRu9Hd35wlbJXWaSEhjm3EHvExC7FAsihKzf3cCkpi3jaUF8pshorbBH2kDfQZ7C8bRiobM01q+DIBwnHulfIaaRcaAUxF7+rEt4JN2e+XV1NspKEfQoDIrdFTNiUYburhkx8irZoRByPDQ1clN
    POSTGRES_PASSWORD: AgCVteGCcHBfv3pw5dIEL+/WaJoNXpWxaGXyYRhb33/iu9/xI+D/ErQvADJ2N3bAtwijbD00WbZYMDCFyXuDqiGYjCfIl2G82h88jwmUAcdWjTNjozoISH4QrCjmqFbAEZ+OY6SpVCFKz2rBNDVivvhwECZ+J+IbKL8BCcE4oNuQBNeRu/9yu7Sn6cGwNrRmm5Sl15ER8UiYBoQ50/Ki+oCQPWUve14cw5kLXDp7+juuWhTEcL7/55JZBJlauXGGL1jVCczF2GxcnsSG6hryZb85pflcKcF+NSsoT/1kUYC/ia8HW8Rk6Aa2rCjsZvX74t9yiWhhU8Cs6Q9rYDz7vVN+KSb760X/HZWSRfZ4FElKLrEJTJG9rSshxRnPXpiBfuRgFkUIyGvOfJSjjcywDaqhh+Sn4mHuj74O8Ia3xUWLWlN93x5kehjsIzULIbzK9X4ryzDPkHqDFq31VE5Z7bVf9BBgYOR0xRP9fexYtZGYpgtbwK/wmJ7l7Yxz/385jzRZUgIFRcPfbgnTn/ZKYB3m/9MdK0Dgiou9OGhdCJ4XJ2yLjcXlAdLlUY9GPT+NOPY69TnchGfzEQlc/TCEYnkyn7bAy4c1nuH685HO5SLVJH/DAtV5tl4a6Fu/6Aks557wAFxtX3hV7aVNaTZHSh4CWNTlQZRo9U3mepr8Onpzy3duumRx9MO5xsJNuJn5trUTImZQstmz//kdSxDjrIxxjkhbxOz3BeUE41oWT/3RDMz9dwRby0eb
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-foundation-strapi-database-secret
      namespace: standalone

