apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-foundation-strapi-meilisearch-secret
  namespace: standalone
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgBYNO0d4+sI8bw5KO7oO2DHbkPqaFUSLqu6qGXszxbNobShG+61R4fxT5lg71EY/KGJTHVLOxeE+0orC0t2oggcMJ6HjEl38lqLzqEGGgC5osTWEltQq2MqFb322rbBklY2kFvsLmDwo1fbO1bGnlbGolUUJxGZ/BPxu6s/enel8rqKnnUL8klah8B1VwvHltw4Zlk72+APGOR3wvAQ3FUBBwZmAMtdxOetVqYsw56pPGjob14BHQ8DAUmcMSPVlrWLwJp3kPgsfEnp9deLQIBzVN2aNpeZ0xRlm/gNBafFLPb9VuNnI5NDEtAqvXHBsl56ZPENVcbbCYh7FF5CSII0f3L60ICjEPf9s33M1kDxfrqtApzJp84AjbsFSjeMhlfB/gAEMFTA+2/MESYktTQ7pnF+0SX9D5S2TR4CJBBPYyOozCUmzSzcyLR0hWn7cnjto6Q13sn08REvjj8xmXRX43RxFP0yLTQyESrXhNb9jkJ0QrJNI9JCrb37XLdw+b1tA9IggtHD9EBxpw92s1UuiopO3c69Xy2eOvnDTBUtK4UChfw60Ake2QolSIq5hKDZLwTSQ7uu25aGnxwQfo3mC4Vzp+tMOFHy0eyZ0G/iHksc7AWNVJOSj51EiQ2AZb8OWSUyK3W4/zS/wVIWpQLPRC+zT8wI+diYFgal/Oi7gpcP8XDoafX8wawCr745YPHgFS0REL0P30SldZcTErJkejDkykWtk/N63hOyNyRWXXd/B3/ytBXMZmHsv2dPg0KL+Hn7vyoVgFEcYBqsi0o=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-foundation-strapi-meilisearch-secret
      namespace: standalone

