apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-foundation-strapi-meilisearch-secret
  namespace: standalone
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgAXaUGmQ/Hv2/6Qgw7TBq4QFh6Cx1QjJ0kmJWm0GLMNEpafOEpZTJ1upsyPLd4iQ6rftU59TIhTJVvxJdwYRLkac0m3njzipRKDl8+gzCNtnxCcQndCPbhjpRpRbPiaorOVTbSkJ/UastPM8P/f5A+iEZ9KbywFhFKAgx2GFdQZEj2V6BrW4qm7hlqhv2he21E2/GrIBwSFAly68aNzOSwm6Mfpt/NzHS3vbgx4m+lMtWEA8z3Gq4V4QxV9ME0gqdCMbfRrCgtFOSgsI2vIVeWCPLq+RzG2pR1HszKrRqPg9Q0JWGmXJeOx4xQnzltukW8nAA6wx3NxEF6yngz6teu14MhPDRDLEsoVP8qGwSHW9iRAc29dSbgJ1b3JjmR+iD0oT6aqyWc+KkeiCe5ykR2TesVSOsmqZQxIBLNacD/mjpeKNJNTkUyLJzNEhirkaSbjmuQ4YtqSs/NFF9kD2qpz/Oy/C1RaCmN2jGu/JvG2OUcoNZJUSDfPiiD4R+m8GPl01fAFQYFce1hK6YyilWxTWxjm/8LhLyvrMTiJPPmwQ4nMEr934MlLrJ3yhooFALPPckuaucLugG7KxM/UzBfSYfSPsLSo9cfL59y/nTmy+rNj6zDNKbm7F6jsjnwUgLBQwwd4AvalIu/Ts0RTklmXzRjRH5e4jzNosDJ0J6SrN0wYRqJVcG1mYMbBojuk8LtNJAzGplRDFYLOS8BkJAFQMXv6etZD022ebiDR2ynNPQU+D0vmvMzHNQQ5P0FCWuiEnSxgjdsQ6AllnYCMvTI=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-foundation-strapi-meilisearch-secret
      namespace: standalone

