apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-foundation-strapi-meilisearch-secret
  namespace: standalone
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgBaq8jcA7oYVCZ0z0geRJK+3p8F0rXWVOUbxBWkmHw8XbUt7CgnDOZz8vHjqAnSvbPaXLIYkmHuXr7EdIA1synku/OvhnWbgtjnA91+bCmSJploN/1GLMrNQPP6VQr3NdPjxrjTwVf5t8nRbNxP1xkw0GlT64f1EMaz4lRVAqUpxeYz55kdhYH08s17nHL7c6twj9pwq9+0VR511Xg6JaHdiehAp/EoQAom2faHWcHp8fJxVxAmcaAkQ2nbRxfsTCBnFzom87e5dFVCOC9ma1QsxUBkHl4cDha97i17f1vJk4XTFJzrih9ZgvfxUT5ch5/XiHlElAeMxJK1+BCRFWcHFv9FopevJdGQh+VplSSfSBSNFbxHQW5UtbLJ5r+MMhWQeNoI9M/08+yVedjWkJnVyCGj1tmBgKVRIzMy/p0jrwbJ5LwRK1yK7zp1DtvDQcvlOxVgjPgXJbEP+MVqbdsp5H+fsihiLmicsFD+K3XFNSWb1mZtZAOuQWc9iE6AkLQte1T66esRPktgSiO504Bm602SwWFrURRUPVGDHW+pbQVGzHILi4di2KoqGuWuGY/61OWhOUn2sSGLFRStiSAsVJ0hvrf4qiyaZX69pZ8H8bNObXW1LQgnDFwvacnSdxKVEp7be99dnvFYgAXoo/GDJvjgTU0ZwAH1eH+R9/2s3qRKYY7f5ZSQyxte7o3Hj2ymTB+CX3GhH++EJUsa8h3kakzH5H8IiOcEvm0cFflVILoFUJ+775ojHMQgnB67VBzDLeCILRj7wkvAWbGHUd8=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-foundation-strapi-meilisearch-secret
      namespace: standalone

