apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-foundation-strapi-plugin-preview-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgA0e07MXGG5ONU8MBZJ+yHRmKfi571k5TJtHHFbwUs+7PKdFWTH+p0IyE3KJpO9kInTp2JIFKsvef3eMv2QO6peumYwQO9GdHF3eOl49j14IEa2zrE2puJjl75XFA/hTCPN8J5ZE0nuNxTbVwgOPDkrn/OZzawKAc8DCUgJhKBc7PDoUmu6MgeWzlxX6oUkt7ZsZeKr0/lUR78apvB2b+BJTYPdosq0149ef/7uYf1t1XFbcc/5fU/m3xztaiIaaIN6S2h3Jy2neETwVr5zlTVFi1YIZt510ly/7cor+yjvDWjuv6Ah1JSIJ9nQAJ47boqRU4Q1bqOsVFoXg4avKQ5wq/6tbD8aWd7AR/MhmyICxPf3JK6/NEL8D8YbnC+sXhRofEvgkw2emXEv8uzKSKr0c0ZeN4PHOy3sb18J8bmRQ6EwKkusvA5ErCk64BHAonSvz/6aIm2/09JFBrqok4Sqs9+KzFQz1otYcnC+GuhjqHRA8jRabsNaeTlYwSfdjd/svJKWSIAMWbuMtD/6GlhB2pV1JI6PdzR+9LhuRMfPZIN+g2wcjF+pLWgk66+038zK4hZENOi9ChtK9QGBcoKib/Az+xrOZEm3j2MQtErlpropTdVAh/FbftEXtokquA71aMVsgQSuoiz0jMJAAs6aqL3iMVH2YU/18d7MqYhs2D5gL5Xbq08IzUmmUqVhO2KPbuQWYhPXQLxzkqyYwip7h1WS6ZjzMi1T9QcQ8Cjebhp83ne4mjmwo2hP2acEYaF8SHi2BKNnQA==
    STRAPI_PREVIEW_SECRET: AgCQQWH/MJXcMICECUUQrZyTMAE9Ksixp+50/trDqlVbGYlpaVP/Qm6VnGrNqBYn/TnumuZjB/Pcs1AUg7cdE0F0mZJlP5m5gS0Ib6uyw1Mdlg+iI76b6bI/kSuhEm/zI64RncOQkjRl7DfufLC9nOI9XrkkAmvKoGa4tuTUEM9ErSMvyZVmCWB6CRFRARIVKli7L4tv3c+d1xQxPBA3YLUkc7Cm5FoAvFV1gTHTaTN2y/iD6sVKwswqTEFMcmUXwpgXvwr4we8adtFsafHvgwsycoZHIWCDEhFqnFKPWmwRzZOs7Sod1GW6ruh0DXvXSsJ3XOkifeuJK1cRIeMAsyAfxxkOQNMssGuHSTFspo3T9qn9OLXZJXt32sYXY848fGYw27m2ZWbN8Ch6OPiprY8TscQSMl03YU+G/HJaqbYbESEpQAJ8Jz3B3YIEeDp1KCm8eKgvNPiMnxaorOGgRq6yJZpW1J2OU7jqfY5dLmEY3UNwj7I9h8BniHDHnCDcsrclW32tbjqouqjKbpK0Z+q3XJedtaeVcv9lfZevAK8mdo/xJqYBXtkr4CyQI1zMwixLRst5UwlqUuie7UqUft9CrMSCZNSCl1fZhR2ZtZd6ZSp9+dmKYDA2wTHkK0g169brJc+EhjK7G+w7b8wcvHtAQk5qOkABaNdYN5BcTc8+yXv4le8aKnH0zY/ojdQ2TA2aFoYm084lDWOSgxVltVTtBm7X3K3gAaUuEo2wSEYZ/+U8szvh27z4XtHKViTeojjnWAqfF7ghFZM=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-foundation-strapi-plugin-preview-secret
      namespace: standalone

