apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-foundation-strapi-plugin-preview-secret
  namespace: standalone
spec:
  encryptedData:
    STRAPI_PREVIEW_SECRET: AgCccu++82/AbJE5OG2krJxraRSSFJVw42GuW/RkckMMDnU4XsBkIIVK/VQjh+mzdiv1OKEDFavimj5DYvr0LXwsS3btLjF8Xh4Q1+xO4Gl9uIyvVk1VjTjGYcITqBoif779NfPS6RqrmgelZTV8zO9AMcEPZUX+s859+JS4g/DR6lGkc/flHgftQo5CyWoSGxErifJAxIARQX7xpuG7GMuw7AjaZZewTNlbmVD4cVyw1EpwTPdi5AZ+LCQnQmL8WQyOGMms82fmDdSlBMB7WP/vZhn7fqkKbFq0RlWf+8JXqON9Q5NrArmXxHq3rNwXxd/oMk0wt6PjiI79IEwOefYsVJOMuQp6BugTnYXjY5IeGoqn87S7TvVpJlsyTNyCTnJWQ0oT0OC8EQvzpajn2YLeKmFy7YgYiVcqIGZADAGGh7QZpwr2r0F5QlW1+327pC06WQGy0ilsPhaBZpmT73VhAOYL6N9kFdmUoAWU1V3PtVwur8Afb0QwKXP77c0N/vNPBVkYIlhCKhVia1YtdPq+5RLGv5Aoc6+CFSjUk/Nmv/Uxm3dSeQXTkNnaNblx1Orni1T/zzFaY7RyoIm4aQrmBVqENjU/Cvn3TtYiT+lF00ZpOVWDPcgBIr8lrJN5CrY2kC5cXXzZ8fZWp3X0MCG8GpOnBOFdqv3JO8balMF1kleBSLK2jnoWgITwrNlktZQyIgIeEmdSDCUYgVyOL2setZ4njDDt/+yV5mSBrRqOGerRk7PDdQVP0nrq
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-foundation-strapi-plugin-preview-secret
      namespace: standalone

