apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-foundation-strapi-plugin-preview-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgA1ee9uk5tsFo1WP2FJqGVNSmx+tgcnwu0m40L30GYkUpfmDdggQxtwKQmZ43OOPF7k6a7Onvbo2leMzMLcDxQX2mmRtyFpzJPFtszTJ28bxMj3N48ee7TMqSZ/AH3JDbcMjd6IzaGsnzCJWGmdI57tBsLtB1QCm56qvY6Uin0LPflORgQCQaGZ6q8K+zOlGWOEUl20KlVbNvz43swleN1h87wBTTHDEnrtsrd4HRjSgjgj4u+I1IN3y890/P/pvEnrbbDJskCZoYIblSqAoo+jAggdLg8Dz3+DIJ39ZNT8cjbsJCoTuhy/D9Q6lLWXR1DSqSxipEM/apKO5E4Qt4lsjQsUCU3MWP0Budj7+mqzF4fSw9Ml0l1IBAjbxgiCn49jpAFA3akQqkrUD2f1xaO5ulUTBRfzvIoWuaFh17EuFgyDU7L2OYxdc+SxZpy0QFy8H5WLnNyiFngS4tQAI9YXduu2I8gyMITHg7KF43DHK6Qiy9968N2C7u1HW+SCH7YvH5bKhCMcShWzW3Gv0G8DFuz9JCxkYxywKpqKlAqvVPAC0x9a9ALWC4kfHY8PvaIIu4iXn0rJk8+4EnIGVBYpheJ7FQ8+6UvnI27VjyznidyKyr7Wvx7jZU8uCKkwwcTzEla83Fxer6zeNrx0rscs3cnv79+rJV9fMPBXzaEzsEc7h2HTQ6Z3EPLGnecA4oRSvZbltHzc9gs/IjwyQyOh7qBwJiZEKTu7XWZTNV7eRleIczUasxN0BzMS5bs4R8iAlRz8m2w=
    STRAPI_PREVIEW_SECRET: AgA28Enptaz1uPQsnReUNdDQLLdQnk6EHFmg4pOra/WIr4rfqR2aqhtPOgrnJzK3v15kPy/oHSSvtnmEEijigxMXJlO1ADI8RQZWOVNlGpMvLxyRjoCtK3hGAgnREj5rJSuqarq3MdxjIrpBIAfKPnRYZi0R6d8IAcvfeoxXSf/tgB/OHFgMRUoEyVOW09Wlkepy/eOW9ejFz3YkXBdgZIe3kSm0rqJY/wReKH48Jnu6iTrJEwoebdKn+Blciz6x4uYAr7CfkM7Mnm3/csye9E08YgC43YiY3GXh1paSlZS4q5xqcX3sgAjyIbq3CiJdtUGOlfJCETkuzYHpeawFOlw6pTduyY5yaOJVftdVwSQQNdlz22Yu4rlqWsL3hm6avsfcW+0WUGqrggjG3RBc6wfMjZcVaLhy/j4yO7oO2SKT+sdcvTXM+/VaCgtPx9JOLzPK5yKm807myYuRN8sQvAjkQVtgPJhiWy/LkZztL/eQ7tSmLCbdfBZSHd7kYEJgfCRhicW0RCGgkek79tF/v3kpFKwrlf0vz5nkjkNVDZgSAjnO6V4IlNrsLp+QmmHa9kNYDJ52cOxC4W4Y86yirvGI6hEXCRkxgCv/ipTmS3fB+tADqV2RBwiIq9trCpp0NUrzr6Ke5L7j2pI2/raFZYgqMPUIshxrmbuFwQb9FeIkNv6knN7ho3oUpi57rKzgFCQQRFWYwc7fd4D0bfCj1rHEgn19/0NBwdaQGAuPSba41afw/hxSWIjYv5fG+y5ATOTEGILE6hk=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-foundation-strapi-plugin-preview-secret
      namespace: standalone

