apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-foundation-strapi-plugin-preview-secret
  namespace: standalone
spec:
  encryptedData:
    STRAPI_PREVIEW_SECRET: AgBGXE03LUUdsUpQn3jAMqpqfhncEDzG6zjNVmqGcP46lq+J+S+sWEgJ4D9qwS/JheT1tMvS/HyBW4Z7swh4JlNNPbR0aG+tJAJS7Q1C3eALoCkwKG1YhOs8vskvyLbWDFq6D5T7dn2Yku28IMw4+YEnJgPB5XY29TiL/uv+5E1AvuUtR2wHTYoO2Xw7EDogkoo7F0ZLwegJA+4NheoZyZofvOJVbP4jWQL5PgA0bZcXbDP7yMeTV/Y1XjlT8IOAPDEDnuat6JiOpNEfeG+ghGIq+WvbnCH2UPUf/TojlcW6hD1P8Xi3lmsFQBGWiaHOFd5tOwSn6P+mp6Z2PLtj9sqHVhQ2tH3GTFIKXV9BITV3j/rA6S39G+C05zV9ftzLGxLnCsDpL1jGE8rXsmQwshtimP1ztiqEiilukOkM4cK978oXza56uu3pMJd1tGdVh9AFpQAQoFgRmv8seYCqLPTZEpD4bFM6LXvFYerCTbuO8LMgk6kb6HFUJkNjg9u0l5puSll1RUUXFmthL4XtT4TmJqsTAIexU5xaVJojL40wxFqrIX5hRzHnsqaHbnYvXQosPu/M/Yv4rzExnrtiL3IPSW2gJQ7A8eEXbhOP3qaCfwHZwRjOgMVCGliwAIjCqi9yLz1zFxUhuCrnFbLugLBrN/aMav3qcOkWo5ORTfvTLEzLqZ5DCxPtQskwshfUNiowIkdo5sBkWMW6oqrTg+3gVneNUUDJpkgk+HqaPh7GCSY+mHbQsngPggs=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-foundation-strapi-plugin-preview-secret
      namespace: standalone

