apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-foundation-strapi-plugin-preview-secret
  namespace: standalone
spec:
  encryptedData:
    STRAPI_PREVIEW_SECRET: AgApzKY5O23RJ4zY7w5z4I0u40ou1QIZa5eKaxtyNytNoUGLGsK2qBT1D+Xc9J4lkXIviEOfUlo2JGO1BwtXrRjfxxYnkKwcIXDmcpPXQJC2bKFeI5yjUrWnZLJ6JVTjIxWdXio3RhVtvWsPfZ2mJJW3SifF9nEgFr2WFu44FsjJNXLmL8n7GVogctWibvyif946Ub3u5ItAHRhmiqPCNH8kUGkV//TdNDtAmwqBvBVRowJJsqdrW4V9ja8J5GCFN8ggpJASt8ZWocUz7e1OKEMWMRtleOro5mLcnjU3h9NjKimwBX0bvQPup0fRVCnlh6WGCbDs3FE3rYV6dAJUqVZumOG4IYtwfUhmenmcsbA/+a+R3hRS48w4oL9slSgcxG5VADWWJNb/BdRfoS1ZnS5EnTqD9LEgHQSGM1iZa0C7UgfheMeYpydf0noa2E7J5dzJ8lZiQM8DLDohLnox+a2LSp/Y+Yqh0xgRGu1q5kZWdX9M3tLO9KCX4yIz9DNgH/IvLeNuOUoDhqxHQYnml74OfFfZN83daTG/6dbMkoHFgSuzmXCrJW/leP45DO3o/BIFTngBqCBCr+z5XOjMzfwCRHmhYfMhMOJPCo10fPv0XDKedqqDBj+U6LBJSDA+Th7D9GmYIVWrPDPENzFGjDtuLj8jjflNk32wNB72vcCDSQkAO45rF0CAdvz5chbicFqKbPUzh4jcxXtr3iUTQ1MAlh+AcX+Ym2BUYBhNHIOxQSGtycYMIrW4+C8W1AIhUP8I7FUueA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-foundation-strapi-plugin-preview-secret
      namespace: standalone

