apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-foundation-strapi-plugin-preview-secret
  namespace: standalone
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgBhUldnIiKJ9E8Y//vlbi2poNrmcPIhiig499879f/P0BtwFJ9GV68l1lkGhPQZGkfUkc0V8qh0MF1MbJNzBAkCuo5jie0XFs853NGoK1CMLF0wEKRlMB477ORKIppGsxakkSe01Det4YsrRwyuD9btjlD4YEsbDoOBM80JM4+ktBsUAm417/XkRqzsiEUL7CivZ4NDOAeQzGEOVNHcUm3CMJpdf3X7sMNyM5YhZiIiyyqEewWfESFI7GiOJ5nHfhlE7hN3dImFro6mdL3W4WIrl7GY9CQbu/tImT9ReiQuOWfht3GB2FJkch+j7S2EqlRF1wXGqNQvzRCknQ+u8Mkwl0nMqmMO41uKoQd1hyPuY933cF2Q4LLtZX0aNiODfs9L5s3qIZ1sYO3QHxUuBidGcBFvy2LY3WDO2AH9iOKTORhz9lyhVcx3FJm2pnIVDoglSWnjdmV6eUJEjClJGKXdBwvBneBwXvEoNjCmyFm1Pi+tLxHoGv2C9U69oO6So2zJ2o8x/3TShv/bOhvqkfU+IOc7s8Ttrg2nS+I65dlJL/ZT4BzQMwquRnF1FPR4caXxDwqjCc7zFMWRvcELfOm4rcyX0xVfs1yCP7p5hmtzxba8++GX2O1rhyC765G64b4IlW1QDSmayfXWeeXM41EvFoRpTcft+DxYwmyN5D8nYXbiZ09EukrxzaIIR5tIw3Tzb3tHNJAvlCqlkQATW6r/WoPPpJZSXgaC8b7GEHAjZKyOB6CReTUTcAlFUQ==
    STRAPI_PREVIEW_SECRET: AgA+s7sv6gX9dJ2a87yrrs7+fDrFcPa6ZAoBI1wmujIv7jyrd6uO4kqvuIQbC/i+aWGUP1AKqJFHHv3Ul4VsB635MbfozrgrYEuD3q2E2h+V5utDiH0kfPv/mFzZGGHvb4e/uQ2PZyFLc+QKg0NLwQ7zRa/N3hwoMcjbRSBx7Uq2h2sY26iL64BZ8cqUqF86SS1CKwbdr27fp3QtnvAtXguNLcD+AQPCTBoyRnmLxpWT4Eu3jLy8eQsCYN2CdA7cVjmS+SKSY2Spr3Fu6Elip5ArL9m3q7C2LoRXfZz1LQN7M1E+yNEMfSbjAT7ie7C/T9u+57ZVv1LBpiqyMzdGSHnEsE2Qp7jQn3iif4f9FPpJfpRAqBrI0DBs/i2lBhSw7HP+LLk2lEmNZPraQ10upPyINSnztsZWjUvL6ArERzewkDhg1aY+gdw8zM/60gqme/LIqkhR16bRzzsz5bEUXPWKWubOhKYwAw5bXZTh61D+Jb0gZDF83/Q3yvBqVMDSB9OWoqwrB80fStirQWbvDKa4ORaVPZlZHKxa9f2q1oZ/7D2ewPN9lNq8kzpfCJyLRMujKjNzkEKK7JLzKQD5YajHOq/cls22PXSAy76yYzfABrNaFuJNIZGadsGhQpogtA99btwIUkHFC/7KIBXnYyfgsnKucenqLfEEKeEA/Y+AHADXkNy6Sh+fIcnSBWHXoL/+VTQSrahBoDmzJymsnQgHlbjbo2mLLC1qNi6topp6VL4XZWshQyuIyXsv6kU=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-foundation-strapi-plugin-preview-secret
      namespace: standalone

