apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: city-gallery-strapi-plugin-preview-secret
  namespace: standalone
spec:
  encryptedData:
    STRAPI_PREVIEW_SECRET: AgDTS1tePPVB2QiQjuWsY40avvTorOagu6Kho4CpGqKsyPVw/T04U17W1pflH4HUS86tJ/UXhXNGsWN85RD94pMJJVhtrLS5AbjCkbR/Nvum2Dw7bNw1zwLD4tiRVmB548vvTvWwI8FqhfkBwEXgi/IoFUskpWSkAhoJjYnQaBaaAFUy/duMA4/ONHDc2ZRmxq/GjmoXrsQLjI1puArWUq3hdZZlRN+HUPNgg2L6cKJ+GLNWWuZmi7EImJoezRXt/PjZjCu/gdK8J0uMxLNTghcbCL0IARg563Zuaq1HQ/V3W6HDII4GV2Yb80PGvuBNlUE8GGQv2LZQr3f58ZEEaUreFPAAOFuQEmq3k+DQ1OU7x6tTlLhqaD3OUgL19TdKGQdEjeGw8g0PhPd7Zwx3GEG2bWfXHrhsru/3Upnil0h629kQtzlFWZ8DXI19HZ27PrAY1YLEFb5sZ0Sgo4Ts71oBszWddLcOm0ICCFvn/A2n9+dny11kGckq5h+odLYolBiV9CS9kVs1V8hrT0MGxTyTi+diT5qqyv9xCbwJaow3seCXySTEExSCXez3XpsCLpf9wKzqeBFioGeaxTb1tSZdkOQwiWgIXt4Ue777AsWKMQTTIjUhDc9zCC5RT9wuqqXeZLW7R1XDSG+ELxLhr2Go4UtMNSiOv07bXLPzp8Xy4Ae/OzUmCu4P+C7Fpv8kuqGloxq/Mm1FAzOZAGc91Ise9mHfrWxRJWA=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: city-gallery-strapi-plugin-preview-secret
      namespace: standalone

